### ISSUE TITLE
Titan's Grip

### ISSUE THREAD

**Issue by LunaEclipse73** [furtrade/EZquip#2]
While playing a fury warrior which has Titan's Grip allowing the use of dual wielding two handed weapons, I noticed this addon defaults to only replacing two handed weapons on the main hand only.  Also because of the dual weilding it seems to prefer to replace two-handed weapons with one handed weapons.

Looking at your code this seems to be because two-handed weapons are set up to only check the main hand, and dual wielding is always set up for one handed weapons.

Perhaps for the dual wielding you can look to see if the player has Titan's Grip ability, and if they do set up dual wielding to use two handed weapons, if they don't to use one handed weapons?

You could try changing TheorizeSet.lua line 70 to the following:

dualWielding = CanDualWield() and (IsPlayerSpell(46917) and { twoHanders[1], twoHanders[2] } or { oneHanders[1], oneHanders[2] }) or {},  -- SpellID 46917 is Fury Warrior's Titan's Grip passive.

**Comment by furtrade** [comment]
Thanks. I'll try to fix it soon.

**Comment by furtrade** [comment]
@LunaEclipse73 
I added the change as you suggested. You should be able to see the change in the beta channel 🤔 I have no way to test right now as I'm not currently subbed. Let me know if the problem persists.

**Comment by LunaEclipse73** [comment]
It seems to be working as expected now, my issues with constantly having to unequip one handed weapons and replace them with two handed weapons is gone.

**Comment by furtrade** [comment]
Cool. Thanks for the intel.
