### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by coastal-ms** [furtrade/EZquip#4]
Not sure the methods but based on your logic, i should be able to set scales and use ez run. Why when i am a prot paladin, using a default prot scale from pawn, does it equip a two hander instead of sword and board? that makes no sense.

**Comment by furtrade** [comment]
Hmmm... I'm on my prot pally right now trying to reproduce that odd behavior. Seems to be working🤔
Are you using a custom pawn scale?
The addon works entirely off of the score produced by pawn. Typically the 'weights' tab in pawn is configured to not provide a value to items that a particular class or spec would not want to equip.

![image](https://github.com/user-attachments/assets/45790492-3f12-4596-abed-10f15a6351e6)

I'll try do some more digging.

**Comment by furtrade** [comment]
I think I've discovered the issue. I'm fairly certain that part of the issue here was the possibility that the addon was trying to equip 2x Two Handers.

Also, my initial assumption that the toggle in pawn weights would set the score to 0 was flawed (╯‵□′)╯︵┻━┻
