### ISSUE TITLE
Feature suggestion: Manual equip trigger

### ISSUE THREAD

**Issue by lmmfranco** [furtrade/EZquip#5]
It would be nice if there was an option to disable the "auto equip all" and leave it as a slash command or button on character frame. Sometimes one may hold on to change equipments at a hub, os sometimes one may just want to use a lower level item for effects, the item changing back automatically makes this a bit hard.

**Comment by furtrade** [comment]
I added a button and a toggle to the character frame. let me know how it goes.

**Comment by lmmfranco** [comment]
It works perfectly. TYVM
