### ISSUE TITLE
Error with the latest version

### ISSUE THREAD

**Issue by MedianAura** [furtrade/EZquip#6]
There are 2 error on login with the newest version 1.0.91

`1x EZquip/Components/TheorizeSet/Accessories.lua:27: attempt to index field 'BisTrinkets' (a nil value)
[string "@EZquip/Components/TheorizeSet/Accessories.lua"]:27: in function `LookupBisTrinkets'
[string "@EZquip/Components/TheorizeSet/Accessories.lua"]:57: in function <EZquip/Components/TheorizeSet/Accessories.lua:54>
[string "@EZquip/Components/TheorizeSet/Accessories.lua"]:157: in function <EZquip/Components/TheorizeSet/Accessories.lua:139>
[string "=(tail call)"]: ?
[string "@EZquip/Components/AdornSet/Phase2.lua"]:13: in function `TheorizeSet'
[string "@EZquip/Components/AdornSet/Phase1.lua"]:52: in function `FindBestItemsAndEquip'
[string "@EZquip/Components/AdornSet/Phase1.lua"]:33: in function `OnEventThrottle'
[string "@EZquip/Main.lua"]:97: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@TomTom/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...aceTomTom/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 defaults = <table> {
 }
 modules = <table> {
 }
 ArmorHandler = <table> {
 }
 hooks = <table> {
 }
 EquippedItems = <table> {
 }
 PreviousQueuedItems = <table> {
 }
 name = "EZquip"
 game = "RETAIL"
 interrupted = false
 inCombat = false
 processing = true
 myArmory = <table> {
 }
 baseName = "EZquip"
 gameVersion = 110002
 defaultModuleState = true
 priorities = <table> {
 }
 enabledState = true
 WeaponHandler = <table> {
 }
 currentIndex = 1
 QueuedItems = <table> {
 }
 optionsFrame = Frame {
 }
 options = <table> {
 }
 db = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 pawn = false
 orderedModules = <table> {
 }
 title = "EZquip"
 invSlots = <table> {
 }
 isInstance = false
 ItemEquipLocToInvSlotID = <table> {
 }
 timeThreshold = 7
 AccessoryHandler = <table> {
 }
 bagSlots = <table> {
 }
}
itemId = 198037
ilvl = 350
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'BisTrinkets' (a nil value)"
`

`1x EZquip/Components/Score.lua:22: attempt to get length of local 'scales' (a nil value)
[string "@EZquip/Components/Score.lua"]:22: in function `getPawnScaleNames'
[string "@EZquip/Options.lua"]:312: in function `GetDefaultScaleForClassOrSpec'
[string "@EZquip/Options.lua"]:298: in function `SetDefaultScaleForSpec'
[string "@EZquip/Options.lua"]:269: in function `InitializeDefaultScales'
[string "@EZquip/Main.lua"]:66: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@TomTom/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...aceTomTom/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
scales = nil
scaleNames = <table> {
}
(*temporary) = 1
(*temporary) = "|cfffe8460ERROR:  |cffffffffCan't get scale list until Pawn is initialized"
(*temporary) = ChatFrame1 {
 systemInfo = <table> {
 }
 shouldFadeAfterInactivity = true
 font = "Interface\AddOns\ElvUI\Core\Media\Fonts\PTSansNarrow.ttf"
 scriptsSet = true
 historyBuffer = <table> {
 }
 styled = true
 overrideFadeTimestamp = 0
 isDisplayDirty = true
 fontSize = 14
 systemPositionDirty = false
 ResizeButton = ChatFrame1ResizeButton {
 }
 settingMap = <table> {
 }
 fontStringPool = <table> {
 }
 ScrollToBottomButton = Button {
 }
 FontStringContainer = Frame {
 }
 isInitialized = 1
 buttonSide = "left"
 dirtySettings = <table> {
 }
 hasActiveChanges = false
 name = "General"
 tab = ChatFrame1Tab {
 }
 isDocked = 1
 isScrollingMessageFrame = true
 ScrollBar = Frame {
 }
 isUninteractable = false
 isLayoutDirty = true
 fontStyle = "OUTLINE"
 copyButton = ElvUI_CopyChatButton1 {
 }
 settingDisplayInfoMap = <table> {
 }
 downKeys = <table> {
 }
 buttonFrame = ChatFrame1ButtonFrame {
 }
 settingsDialogAnchor = <table> {
 }
 snappedFrames = <table> {
 }
 onDisplayRefreshedCallbacks = <table> {
 }
 visibleLines = <table> {
 }
 oldestFadingLineTimestamp = Infinite
 textIsCopyable = false
 scrollOffset = 0
 fadeDurationSecs = 3
 timeVisibleSecs = 100
 hasOwnFontObject = true
 EditModeResizeButton = Button {
 }
 allowScroll = true
 editBox = ChatFrame1EditBox {
 }
 oldAlpha = 0.156863
 channelList = <table> {
 }
 Background = ChatFrame1Background {
 }
 messageTypeList = <table> {
 }
 savedSystemInfo = <table> {
 }
 allowAtGlues = true
 system = 8
 fontObject = table: 000002BDDB863B70 {
 }
 systemNameString = "Chat Frame"
 zoneChannelList = <table> {
 }
 insertMode = 2
 Selection = Frame {
 }
 clickAnywhereButton = ChatFrame1ClickAnywhereButton {
 }
 isStaticDocked = true
 isLocked = true
}
(*temporary) = "attempt to get length of local 'scales' (a nil value)"
`

**Comment by furtrade** [comment]
Thanks for report. I'm looking into it now.
